swagger: "2.0"
info:
  description: This is the official API for the `ad-infinitum` project.
  version: "1.0.0"
  title: Ad-Infinitum
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /people:
    get:
      operationId: "people.read"
      tags:
        - "People"
      summary: "The people data structure supported by the server application"
      description: "Read the list of people"
      responses:
        200:
          description: "Successful read people list operation"
          schema:
            type: "array"
            items:
              properties:
                first_name:
                  type: "string"
                last_name:
                  type: "string"
                birth_date:
                  type: "string"

    post:
      operationId: people.create
      tags:
        - People
      summary: Create a person
      description: Create a new person
      parameters:
        - name: person
          in: body
          description: Person to create
          required: True
          schema:
            type: object
            properties:
              first_name:
                type: string
                description: First name of person to create
              last_name:
                type: string
                description: Last name of person to create
              birth_date:
                type: string
                description: Date of birth of the person to create
      responses:
        201:
          description: Successfully created person
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              birth_date:
                type: string
                description: Creation/Update birth_date of the person record

  /people/{person_id}:
    get:
      operationId: people.read_one
      tags:
        - People
      summary: Read one person
      description: Read one person
      parameters:
        - name: person_id
          in: path
          description: Id of the person to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read person from people data operation
          schema:
            type: object
            properties:
              person_id:
                type: string
                description: Id of the person
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              birth_date:
                type: string
                description: Creation/Update birth_date of the person record

    put:
      operationId: people.update
      tags:
        - People
      summary: Update a person
      description: Update a person
      parameters:
        - name: person_id
          in: path
          description: Id the person to update
          type: integer
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
      responses:
        200:
          description: Successfully updated person
          schema:
            properties:
              person_id:
                type: string
                description: Id of the person in the database
              first_name:
                type: string
                description: First name of the person
              last_name:
                type: string
                description: Last name of the person
              birth_date:
                type: string
                description: Creation/Update birth_date of the person record

    delete:
      operationId: people.delete
      tags:
        - People
      summary: Delete a person from the people list
      description: Delete a person
      parameters:
        - name: person_id
          in: path
          type: integer
          description: Id of the person to delete
          required: true
      responses:
        200:
          description: Successfully deleted a person

